[package]
name = "mango"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.3.5"
num_cpus = "1.13.1"
flume = "0.10.12"
crossbeam-channel = "0.5.4"

[dependencies]
likely_stable = "0.1.2"

[[bench]]
name = "benchmarks"
harness = false